version: '3'
services:
  app:
    build: .
    environment:
      PORT: 3030
      NODE_ENV: production
      PRO_DB_HOST: mongodb
      PRO_DB_PORT: 27017
      PRO_DB_NAME: ECommerce
    ports:
      - '3030:3030'
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
